[tool.poetry]
name = "seq-gfn"
version = "0.1.0"
description = ""
authors = ["listar2000 <35262801+listar2000@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torchgfn = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
